name: "编译内核模块"

on:
  workflow_dispatch:

jobs:
  Set-repos:
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout"
        uses: actions/checkout@main

      - name: Free Disk Space
        run: |
          sudo docker image prune -a -f
        
      - name: "Install prerequisites"
        run: |
          sudo apt-get update
          sudo apt-get install -y bc gcc wget python-is-python3 rsync bison flex

      - name: "Downloading repo"
        run: |
          mkdir -p ~/bin
          curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
          chmod a+x ~/bin/repo
          echo "~/bin" >> $GITHUB_PATH

      - name: "Clone kernel modules"
        run: |
          mkdir workspace
          cd workspace
          repo init -u https://github.com/OnePlusOSS/kernel_manifest.git -b oneplus/sm8750 -m oneplus_13t_b.xml --depth=1
          repo sync -j$(nproc)

      - name: "Build kernel modulse"
        run: |
          cd workspace
          ./kernel_platform/oplus/build/oplus_build_kernel.sh sun perf
          
